services:
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    volumes:
      - ./build/local/nginx/templates:/etc/nginx/templates
      - ./app:/opt/back
    ports:
      - ${APP_PORT}:80
    depends_on:
      - backend

  backend:
    image: thecodingmachine/php:8.3-v4-fpm
    platform: linux/amd64
#    user: "${WWWUSER}:${WWWGROUP}"
    volumes:
#      - ./build/local/php/conf.d/spx.ini:/etc/php/conf.d/100_spx.ini:ro
      - ./build/local/php/php-fpm.d/custom.conf:/etc/php/8.3/fpm/pool.d/x-www-custom.conf:ro
      - ./app:/opt/back
    working_dir: /opt/back
    environment:
      PHP_EXTENSION_XDEBUG: 1
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_SESSION: ${XDEBUG_SESSION}
      XDEBUG_CONFIG: "client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_REMOTE_PORT}"
      PHP_IDE_CONFIG: "serverName=${XDEBUG_IDE_SERVER_NAME}"
    depends_on:
      - database
#        condition: service_healthy

  database:
    image: mysql:8.0.34
    platform: linux/amd64
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - ${DATABASE_PORT}:3306
    command: --bind-address=0.0.0.0
#    healthcheck:
#      test: [ "CMD-SHELL", "/usr/bin/mysql --user=root --password=\"$DATABASE_ROOT_PASSWORD\" --execute \"SHOW DATABASES;\" | grep \"$DATABASE_NAME\"" ]
#      interval: 2s
#      timeout: 10s
#      retries: 3
#      start_period: 30s
#      start_interval: 1s

volumes:
  database-data:
